version: "3.8"
services:
  app:
    build: .
    container_name: ai_toolbox_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
  mongo:
    image: mongo:7
    container_name: ai_toolbox_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
